# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c942d4cca382e9da350f3e1fab2a036517f63754cc63ab9d41dce6dfa3eea092ea44f92c787c5b67dd26730cd381a380d300ae3fbd2ac2e9f89616a42e4fc1c8

test:
  secret_key_base: 8159d2b5ddaacb8e1dbb86fcda1e37111f357cff4a59d1f32abb53c56031046a5ae989a749e15f2b295c8c5c18d0e1e9dc4a9167a87e5d4221e3378faf431cd7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
